# Generated by Django 4.1.6 on 2023-05-18 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oceanicexpress', '0003_rename_logins_login_rename_signups_signup'),
    ]

    operations = [
        migrations.CreateModel(
            name='adminlogin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50, verbose_name='Username')),
                ('password', models.CharField(max_length=50, verbose_name='Password')),
            ],
        ),
    ]
