# Generated by Django 4.1.6 on 2023-05-20 22:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('oceanicexpress', '0004_adminlogin'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='login',
            new_name='logincred',
        ),
        migrations.RenameModel(
            old_name='signup',
            new_name='signupcred',
        ),
    ]
